apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: eduazureregistry1002.azurecr.io/backend-java
    newTag: main-20240724075620

commonLabels:
  app: backend-java
  environment: dev
